prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix :        <http://www.me-datastudio.nl/vocabularies/voertuig#>

SELECT DISTINCT ?class ?label ?val
WHERE {
  ?class a :v312 .
  ?class :heeftKwaliteit ?kwal .
  ?kwal a ?classAtt .
  ?classAtt rdfs:label ?label .
  ?kwal :heeftWaarde ?val .
}
LIMIT 25
