PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix : <http://www.me-datastudio.nl/vocabularies/voertuig#>

insert { ?s2 owl:sameAs ?uri .}
where{
  ?s2 :heeftWaarde ?val .
  ?s2 rdf:type ?s .
  ?s rdfs:label "Plaats"@nl .

  
  BIND ("http://dbpedia.org/resource/" AS ?base)
 
  BIND (IRI(CONCAT(?base,  CONCAT(UCASE(SUBSTR(?val,1,1)),LCASE(SUBSTR(?val,2))))) AS ?uri) #Plaatsnaam omzetten naar beginnen met Hoofdletter en rest kleine letters
  
}
